<a href="https://colab.research.google.com/github/SatyaThakur/Deep-Learning/blob/master/Boston_House_Prices_Normalization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
pip install tensorflow==1.14.0

     |████████████████████████████████| 109.2MB 97kB/s 
     |████████████████████████████████| 3.2MB 54.4MB/s 
     |████████████████████████████████| 491kB 58.2MB/s 
  Found existing installation: tensorboard 2.2.1
    Uninstalling tensorboard-2.2.1:
      Successfully uninstalled tensorboard-2.2.1
  Found existing installation: tensorflow-estimator 2.2.0
    Uninstalling tensorflow-estimator-2.2.0:
      Successfully uninstalled tensorflow-estimator-2.2.0
  Found existing installation: tensorflow 2.2.0rc4
    Uninstalling tensorflow-2.2.0rc4:
      Successfully uninstalled tensorflow-2.2.0rc4


# Setup check

In [0]:
#Importing tensorflow 
import tensorflow as tf

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or 

In [0]:
import tensorflow as tf
tf.__version__

'1.14.0'

In [0]:
sess = tf.Session()

In [0]:
hello = tf.constant("Hello World")
print(sess.run(hello))

b'Hello World'


# Boston House Prices Normalization


In [0]:
import numpy as np

In [0]:
tf.reset_default_graph()

In [0]:
from tensorflow.contrib.learn import datasets
boston = datasets.load_dataset('boston')

Instructions for updating:
Please use tf.data.
Instructions for updating:
Use scikits.learn.datasets.
Instructions for updating:
Use tf.data instead.


In [0]:
boston

Dataset(data=array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]]), target=array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 

In [0]:
boston.data

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [0]:
boston.target

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [0]:
features = np.array(boston.data)
prices = np.array(boston.target)


In [0]:
features

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [0]:
prices

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [0]:
prices.shape

(506,)

In [0]:
prices = np.reshape(prices, [-1,1])
prices.shape

(506, 1)

# Building the graph

In [0]:
#input features
#13 is the column value of data
x = tf.placeholder(shape = [None,13], dtype=tf.float32, name='x_input')
#actual output
y_ = tf.placeholder(shape = [None,1], dtype=tf.float32, name='y_input')

In [0]:
x

<tf.Tensor 'x_input_1:0' shape=(?, 13) dtype=float32>

In [0]:
y_

<tf.Tensor 'y_input_1:0' shape=(?, 1) dtype=float32>

**Normalizing Data**

In [0]:
x_n = tf.nn.l2_normalize(x,1)

In [0]:
x_n

<tf.Tensor 'l2_normalize_1:0' shape=(?, 13) dtype=float32>

Defining weights and bias

In [0]:
#defining variables for weight and bias ands initializing with 0
W = tf.Variable(tf.zeros(shape=[13,1]), name="Weights")
b = tf.Variable(tf.zeros(shape=[1]), name="Bias")

**Placeholder vs Variable**

Placeholder: These are something where we dont initial its value coz value is provided dynamically.

Variable: The value is initialized.

In [0]:
#logic: y=wx+b
#predicted value(y)
y=tf.add(tf.matmul(x_n,W),b, name="output")

In [0]:
#logic: l = summation & mean((actual - predicted)^2 )
loss = tf.reduce_mean(tf.square(y-y_), name="Loss")

Loss Optimizer

In [0]:
train_op = tf.train.GradientDescentOptimizer(0.3).minimize(loss)
#learning rate = 0.3

#same thing we can do with sklearn like:
#model = sklearn.LinearRegression(c=0.1).fit(x,y)
#model.predict(x)
#model.score(model.predict(x),y)

# Executing the Graph

In [0]:
# with commands works like for loop or speciically while loop

with tf.Session() as sess: 
  #now actual loading of varibles will take place
  sess.run(tf.global_variables_initializer())

  #no of times data should be shown to the model
  training_epochs = 1000

  for epoch in range(training_epochs):

    #calculate train_op and loss
    train_model, train_loss = sess.run([train_op, loss], feed_dict={x:features, y_:prices})

    if epoch % 100 == 0:
      print("Training loss at step: ", epoch , " is ", train_loss)
      print(sess.run([W,b])) 

Training loss at step:  0  is  592.1469
[array([[4.32547331e-02],
       [4.04179662e-01],
       [2.30038390e-01],
       [2.18372745e-03],
       [1.33205717e-02],
       [1.65701985e-01],
       [1.58091342e+00],
       [1.05650045e-01],
       [1.80430993e-01],
       [8.93021965e+00],
       [4.53555495e-01],
       [9.44905281e+00],
       [2.55974799e-01]], dtype=float32), array([13.519686], dtype=float32)]
Training loss at step:  100  is  62.925106
[array([[-9.8305494e-01],
       [ 6.4261389e+00],
       [-1.1337256e+00],
       [ 3.8940318e-02],
       [ 6.4115399e-03],
       [ 7.4250531e-01],
       [-1.9799654e+00],
       [ 2.4457292e-01],
       [-1.1225989e-01],
       [-2.7040744e+00],
       [ 9.9742906e-03],
       [ 1.8946001e+01],
       [-3.0634100e+00]], dtype=float32), array([12.0937], dtype=float32)]
Training loss at step:  200  is  61.63997
[array([[-1.5933676e+00],
       [ 1.0844517e+01],
       [-2.0546739e+00],
       [ 7.4750654e-02],
       [ 3.2926120e-

We can see the bias is very high(21.065) which is not good, it seems like x and y mapping is not good.

In this condition we can do 2 things, either we can **increase the epoch steps** or we can **reduce the learning rate**.

But when we decrease the learning rate, our loss becomes higher and bias got reduced and vice versa. Same with the epoch steps. we need to find out the best outcome.

In [0]:
#summary is the tf operation that create protocol buffers containing summarized data
training_loss = tf.summary.scalar('train_loss', loss)

In [0]:
training_loss

<tf.Tensor 'train_loss:0' shape=() dtype=string>